name: Tests
on: push

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup python
        uses: actions/setup-python@v3
        with:
          python-version: 3.11.3

      - name: Install tools
        run: python -m pip install --upgrade pip pytest
      
      - name: Install Requests
        run: python -m pip install --upgrade pip requests
     
      - name: Install SQLAlcehmy
        run: python -m pip install --upgrade pip sqlalchemy
        
      - name: Install pandas
        run: python -m pip install --upgrade pip pandas

      - name: Test with unittest
        run: python3 -m unittest testCurr.py
